name: Deploy MarkBind Site
on:
  push:
    branches: main

jobs: 
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy MarkBind site
        uses: SPWwj/markbind@branch-qr-code
        with:
          token: ${{ secrets.RepoMb }}
